version: '2.3'
services:
  app:
    build: ./app/
    depends_on:
      - db
    networks:
      - net
    ports:
      - ${APP_PORT:-8000}:80/tcp
    volumes:
      # configuration file
      - type: bind
        source: ./config.toml
        target: /etc/xo-server/config.toml
      # data directory
      - type: volume
        source: data_app
        target: /var/lib/xo-server/data/
      # timezone 
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
  db:
    image: redis:latest
    networks:
      - net
    volumes:
      # data directory
      - type: volume
        source: data_db
        target: /data/
     # timezone 
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
networks:
  net:
    driver: bridge
volumes:
  data_app:
  data_db:

# vim: et sw=2 ts=2
