#!/usr/bin/env bash

set -euo pipefail

dstdir=${1:-/etc/bind}
dstpath="$dstdir/zones.invalid"
srcpath="$(mktemp -t)"
blacklist="$(mktemp -t)"
whitelist="$(mktemp -t)"
trap 'rm -f "$srcpath" "$blacklist" "$whitelist"' EXIT

declare -r curlopts='--fail --location --show-error --silent'

#
# blacklists
#

echo "Downloading blacklist from EnergizedProtection"
curl $curlopts https://block.energized.pro/spark/formats/domains.txt \
  | grep --invert-match '^#' \
  >>"$blacklist"

# add another blacklist (remote)
#echo "Downloading another blacklist"
#curl $curlopts https://www.example.com/path/to/list >>"$blacklist"

# add another blacklist (local)
#echo "Copying another blacklist"
#cat /path/to/list >>"$blacklist"

#
# whitelists
#

echo "Downloading whitelist from anudeepND"
curl $curlopts https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt \
  >>"$whitelist"

# add another whitelist (remote)
#echo "Downloading another whitelist"
#curl $curlopts https://www.example.com/path/to/list >>"$whitelist"

# add another whitelist (local)
#echo "Copying another whitelist"
#cat /path/to/list >>"$whitelist"

echo "Merging blacklists"
sort --output="$blacklist" --unique "$blacklist"

echo "Merging whitelists"
sort --output="$whitelist" --unique "$whitelist"

echo "Generating preliminary zone statements"
for domain in $(comm -23 "$blacklist" "$whitelist"); do
	printf "zone \"%s\" { type master; file \"/etc/bind/db.null\"; };\n" "$domain" >>"$srcpath"
done

rc=0
if cmp --silent "$srcpath" "$dstpath"; then
	echo "There were no changes"
	rc=3
else
	echo "Copying zone statements to $dstpath"
	install --mode=644 "$srcpath" "$dstpath"
fi
exit $rc

# vim: noet sw=8 ts=8
