#!/usr/bin/env bash

set -euo pipefail

declare -r dstdir=${1:-/etc/bind}
declare -r dstpath="$dstdir/zones.invalid"

declare -r srcpath="$(mktemp -t)"
declare -r blacklist="$(mktemp -t)"
declare -r whitelist="$(mktemp -t)"
trap 'rm -f "$srcpath" "$blacklist" "$whitelist"' EXIT

declare -r cachedir="/var/local/cache/${0##*/}"
mkdir -p "$cachedir"

declare -r wgetopts='--quiet --timestamping'

pushd "$cachedir" >/dev/null

#
# blacklists
#

echo "Downloading blacklist from EnergizedProtection"
downloadname='domains.txt'
wget2 $wgetopts https://block.energized.pro/spark/formats/$downloadname
grep --invert-match '^#' $downloadname >>"$blacklist"

# add another blacklist (remote)
#echo "Downloading blacklist from ..."
#downloadname='example.txt'
#wget2 $wgetopts https://www.example.com/path/to/$downloadname
#cat $downloadname >>"$blacklist"

# add another blacklist (local)
#echo "Copying blacklist from ..."
#cat /path/to/list >>"$blacklist"

#
# whitelists
#

echo "Downloading whitelist from anudeepND"
downloadname='whitelist.txt'
wget2 $wgetopts https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/$downloadname
cat $downloadname >>"$whitelist"

# add another whitelist (remote)
#echo "Downloading whitelist from ..."
#downloadname='example.txt'
#wget2 $wgetopts https://www.example.com/path/to/$downloadname
#cat $downloadname >>"$whitelist"

# add another whitelist (local)
#echo "Copying whitelist from ..."
#cat /path/to/list >>"$whitelist"

popd >/dev/null

echo "Merging blacklists"
sort --output="$blacklist" --unique "$blacklist"

echo "Merging whitelists"
sort --output="$whitelist" --unique "$whitelist"

echo "Generating preliminary zone statements"
for domain in $(comm -23 "$blacklist" "$whitelist"); do
	printf "zone \"%s\" { type master; file \"/etc/bind/db.null\"; };\n" "$domain" >>"$srcpath"
done

rc=0
if cmp --silent "$srcpath" "$dstpath"; then
	echo "There were no changes"
	rc=3
else
	echo "Copying zone statements to $dstpath"
	install --mode=644 "$srcpath" "$dstpath"
fi
exit $rc

# vim: noet sw=8 ts=8
